#!/usr/bin/env bash
# Export the hermetic dependency install trees into <workspace>/deps/ so the
# plain CMake flow can build without system-installed libraries:
#
#   bazelisk run //:deps
#   cmake -B build -DCMAKE_TOOLCHAIN_FILE=$PWD/deps/toolchain.cmake
#
# Strictly opt-in: the CMake-with-system-packages flow is unaffected unless
# the toolchain file is passed. deps/ is git- and bazel-ignored and fully
# regenerated on every run (safe to delete at any time).
set -euo pipefail

if [[ -z ${BUILD_WORKSPACE_DIRECTORY:-} ]]; then
  echo >&2 "error: must be invoked via 'bazel run //:deps'"
  exit 1
fi

CAPNPROTO_PREFIX=$1
ONETBB_PREFIX=$2
BOOST_VERSION_HPP=$3 # sentinel file; boost root is two levels up
FLEXLEXER_H=$4
shift 4 # remaining args: zlib outputs (libz.a, libz.so) + public headers

DEST="${BUILD_WORKSPACE_DIRECTORY}/deps"
STAGE="${DEST}.tmp"
# A stale stage from an interrupted run may carry read-only bits.
[ -d "${STAGE}" ] && chmod -R u+w "${STAGE}"
rm -rf "${STAGE}"
mkdir -p "${STAGE}/include" "${STAGE}/lib"

# Merge the cmake install prefixes (bin/ include/ lib/ lib/cmake/) into one
# CMake prefix. -L dereferences tree-artifact symlink chains (libtbb.so.12,
# capnpc) so deps/ survives 'bazel clean'. The CapnProto/TBB package configs
# stay valid after copying: they compute _IMPORT_PREFIX relative to their own
# location.
cp -RL --no-preserve=mode,timestamps "${CAPNPROTO_PREFIX}"/. "${STAGE}/"
cp -RL --no-preserve=mode,timestamps "${ONETBB_PREFIX}"/. "${STAGE}/"

# Header-only and single-file deps.
cp -RL --no-preserve=mode,timestamps "$(dirname "$(dirname "${BOOST_VERSION_HPP}")")/boost" "${STAGE}/include/boost"
cp -L --no-preserve=mode,timestamps "${FLEXLEXER_H}" "${STAGE}/include/"
# zlib: static archive + public headers (skip libz.so — CMake consumers
# should link the static archive, and a solib copy would dangle).
for f in "$@"; do
  case "${f}" in
    *.a) cp -L --no-preserve=mode,timestamps "${f}" "${STAGE}/lib/" ;;
    *.h) cp -L --no-preserve=mode,timestamps "${f}" "${STAGE}/include/" ;;
  esac
done

# v1 toolchain file: dependency resolution only. The hermetic compiler export
# (CMAKE_C/CXX_COMPILER + zero-sysroot flags) lands with the hermetic-llvm
# toolchain switch; until then the host compiler is ABI-compatible with these
# libraries (both GCC/libstdc++).
cat > "${STAGE}/toolchain.cmake" <<'EOF'
# Generated by 'bazel run //:deps' — do not edit.
get_filename_component(_KF_DEPS "${CMAKE_CURRENT_LIST_DIR}" ABSOLUTE)
list(APPEND CMAKE_PREFIX_PATH "${_KF_DEPS}")
set(Boost_INCLUDE_DIR "${_KF_DEPS}/include" CACHE PATH "")
set(FLEX_INCLUDE_DIR "${_KF_DEPS}/include" CACHE PATH "")
set(ZLIB_ROOT "${_KF_DEPS}" CACHE PATH "")
EOF

# Belt and braces on top of the repo .gitignore/.bazelignore entries.
printf '*\n' > "${STAGE}/.gitignore"

chmod -R u+w "${STAGE}"
rm -rf "${DEST}"
mv "${STAGE}" "${DEST}"

echo "Hermetic dependencies exported to ${DEST}"
echo "Use with: cmake -B build -DCMAKE_TOOLCHAIN_FILE=${DEST}/toolchain.cmake"
