load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "tbb",
    hdrs = glob([
        "include/boost/**/*.h",
        "include/boost/**/*.hpp",
        "include/oneapi/**/*.h",
        "include/tbb/**/*.h",
    ]),
    includes = ["include"],
    linkopts = [
        "-L/opt/homebrew/lib",
        "-L/usr/local/lib",
        "-ltbb",
        "-ltbbmalloc",
    ],
    visibility = ["//visibility:public"],
)
