load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//bazel:naja_includes.bzl", "NAJA_HEADER_COPTS")

cc_library(
    name = "kepler_clocks",
    srcs = [
        "SecClockModel.cpp",
    ],
    hdrs = [
        "SecClockModel.h",
    ],
    includes = [
        "..",
        "../formal",
        "../sec",
    ],
    copts = NAJA_HEADER_COPTS,
    visibility = ["//visibility:public"],
    deps = [
        "//src/formal:formal_structures",
        "//src/strategies:formal_strategies",
    ],
)
